version: "3.9"

#services:
#  mongo:
#    image: mongo:latest
#    restart: unless-stopped
#    env_file: ./.env
#    ports:
#      - ${MONGO_LOCAL_PORT}:${MONGO_DOCKER_PORT}
#
#  nats:
#    image: nats:latest
#    env_file: ./.env
#    ports:
#      - ${DEFAULT_NATS_LOCAL_PORT}:${DEFAULT_NATS_DOCKER_PORT}
#      - ${CLUSTER_NATS_LOCAL_PORT}:${CLUSTER_NATS_DOCKER_PORT}
#      - ${MONITORING_NATS_LOCAL_PORT}:${MONITORING_NATS_DOCKER_PORT}
#
#  app:
#    depends_on:
#      - mongo
#      - nats
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    env_file: ./.env
#    ports:
#      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
#    environment:
#      - "SPRING_PROFILES_ACTIVE=docker"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

