version: "3.9"

services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${MONGO_LOCAL_PORT}:${MONGO_DOCKER_PORT}
  app:
    depends_on:
      - mongo
    image: ajax-onboarding-project
    build: .
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
                "spring.data.mongodb.database" : "test",
                "spring.data.mongodb.host" : "mongo",
                "spring.data.mongodb.port" : "27017",
                "security.jwt.token.secret_key" : "SECRET",
                "security.jwt.token.expire_length" : "3700000"
              }'