name: Java with Gradle CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read


jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - ${{ env.MONGO_LOCAL_PORT }}:${{ env.MONGO_DOCKER_PORT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew build

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Wait for Services to Start
        run: docker-compose ps

      - name: Run Tests
        run: ./gradlew test

      - name: Stop Docker Compose
        run: docker-compose down
