name: Java with Gradle CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
        mongo:
          image: mongo:latest
          ports:
            - 27017:27017
          options: >-
            --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with gradle
        run: ./gradlew build
